---
title: "Poisson structural time series model"
author: "Jouni Helske"
date: "25 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stannis)
library(rstan)
```

## Data

```{r data}
set.seed(123)
n <- 500
k <- 3
x1 <- rnorm(n, mean = 1, sd = 0.1)
x2 <- cumsum(rnorm(n, sd = 0.05))
x3 <- runif(n, 0, 1)
xreg <- cbind(x1, x2, x3)
slope <- cumsum(c(0, rnorm(n-1, sd = 0.0005)))
y <- rpois(n, exp(rowSums(xreg) + cumsum(slope + c(0, rnorm(n - 1, sd = 0.1)))))
ts.plot(y)
```

```{r stannis, cache = TRUE}
dat <- as.data.frame(cbind(y, xreg))
names(dat) <- c("y", paste0("x", 1:3))
bsm_out <- stannis(y ~ ., dat, distribution = "poisson", iter = 2000, thin = 1,
                   beta = cbind(0, rep(2, k)), level = c(0, 1), slope = c(0, 1),
                   x1 = c(0, 0), P1 = diag(c(10, 1)), n_threads = 2)

```

```{r stan, cache = TRUE}
stan_data <- list(n = n, k = k, y = y, xreg = xreg, x1 = c(0,0), P1 = diag(c(10, 1)), 
                  sd_prior_means = c(0, 0), sd_prior_sds = c(1, 1), 
                  beta_prior_means = rep(0, k), beta_prior_sds = rep(2, k))

stan_inits <- list(
  list(theta = c(0.01, 0.0001), beta = rep(0, k), level_std = rep(0, n), slope_std = rep(0, n)), 
  list(theta = c(0.1, 0.1), beta = rep(1, k), level_std = rep(0, n), slope_std = rep(0, n)),
  list(theta = c(0.0001, 0.01), beta = rep(-1, k), level_std = rep(0, n), slope_std = rep(0, n)),
  list(theta = c(0.001, 0.001), beta = rep(0, k), level_std = rep(0, n), slope_std = rep(0, n)))

fit <- sampling(stannis:::stanmodels$x_llt_poisson, data = stan_data, seed = 1,
                iter = 2000, thin = 1,  chains = 4, init = stan_inits)
```

```{r results}
print(bsm_out$stan_fit,pars = c("beta", "theta"))
print(fit,pars = c("beta", "theta"))

```
