// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// R_is_correction_bsf
Rcpp::List R_is_correction_bsf(const Rcpp::List& model_, const arma::mat& theta, const arma::vec& approx_posterior, const unsigned int nsim_states, const arma::vec& prior, const unsigned int n_threads, const unsigned int seed);
RcppExport SEXP StanIS_R_is_correction_bsf(SEXP model_SEXP, SEXP thetaSEXP, SEXP approx_posteriorSEXP, SEXP nsim_statesSEXP, SEXP priorSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model_(model_SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type approx_posterior(approx_posteriorSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nsim_states(nsim_statesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(R_is_correction_bsf(model_, theta, approx_posterior, nsim_states, prior, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
