# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_is_correction <- function(model_, approx_y, approx_var_y, scales, theta, approx_posterior, jacobian, nsim_states, n_threads, seed) {
    .Call(stannis_R_is_correction, model_, approx_y, approx_var_y, scales, theta, approx_posterior, jacobian, nsim_states, n_threads, seed)
}

